export const copy = {
  en: {
    nav: {
      features: "Features",
      pricing: "Pricing",
      faq: "FAQ",
      login: "Log in",
      getStarted: "Get Started",
      dashboard: "Dashboard",
      opportunities: "Opportunities",
      drafts: "Drafts",
      workspace: "Workspace",
      billing: "Billing",
      logout: "Log out",
      settingsGroup: "Settings",
      menuGroup: "Menu",
    },
    landing: {
      badge: "Your X Growth Copilot",
      heroTitle: "Stop scrolling. Start growing.",
      heroSubtitle:
        "Discover the best opportunities to post, quote, and reply on X. Organize your content. Build your audience with intention.",
      heroCta: "Start Free Trial",
      heroSecondaryCta: "See How It Works",
      problemTitle: "Growing on X shouldn't feel like a full-time job",
      problemSubtitle:
        "Most creators waste hours scrolling, miss high-impact opportunities, and lose track of their best ideas. Xsaas changes that.",
      problemCards: {
        scroll: { title: "Endless Scrolling", description: "Hours lost searching for the right posts to engage with" },
        missed: { title: "Missed Opportunities", description: "Viral threads pass by before you can contribute" },
        ideas: { title: "Lost Ideas", description: "Your best draft ideas scattered across notes apps" },
      },
      featuresTitle: "Everything you need to grow strategically",
      featuresSubtitle: "Curated opportunities, organized drafts, and insights that actually matter.",
      features: {
        post: {
          title: "Post Opportunities",
          description: "Spot timely topics worth posting about before the timeline gets saturated.",
        },
        quote: {
          title: "Quote Opportunities",
          description: "Find posts worth quoting while they still have momentum and room for your angle.",
        },
        reply: {
          title: "Reply Opportunities",
          description: "Track discussions where a smart reply can actually move attention toward your profile.",
        },
        drafts: {
          title: "Draft Workspace",
          description: "Keep ideas, hooks, and ready-to-publish drafts in one organized place.",
        },
        analytics: {
          title: "Growth Analytics",
          description: "Understand what is working so you can publish with more confidence and less guesswork.",
        },
        schedule: {
          title: "Smart Scheduling",
          description: "Prepare content ahead of time and stay consistent without living inside the app.",
        },
      },
      howItWorksTitle: "How it works",
      howItWorksSubtitle: "Get started in minutes, see results in days.",
      steps: {
        connect: {
          title: "Connect Your Account",
          description: "Link your X workflow and define the topics, tone, and angles you care about.",
        },
        discover: {
          title: "Discover Opportunities",
          description: "Review high-signal posting, quote, and reply opportunities ranked by relevance.",
        },
        create: {
          title: "Create and Organize",
          description: "Turn ideas into drafts, keep your best angles, and stay ready to publish.",
        },
        grow: {
          title: "Grow With Intention",
          description: "Use better timing, stronger context, and cleaner organization to build momentum.",
        },
      },
      pricingTitle: "Simple, transparent pricing",
      pricingSubtitle: "Start free. Upgrade when you're ready to accelerate.",
      faqTitle: "Frequently asked questions",
      faqSubtitle: "Everything you need to know about Xsaas.",
      faqs: [
        {
          question: "How does Xsaas find opportunities?",
          answer:
            "Xsaas combines your workspace preferences with platform signals to surface posting, quote, and reply moments worth your attention.",
        },
        {
          question: "Is my X account secure?",
          answer:
            "The product is designed around minimal permissions and workspace separation. Authentication and publishing flows are handled on the server side.",
        },
        {
          question: "Can I cancel anytime?",
          answer: "Yes. Your subscription can be changed or cancelled whenever you need.",
        },
        {
          question: "Does Xsaas post everything automatically?",
          answer:
            "The product is built to support automation with guardrails. You can decide which parts stay manual and which parts become automatic.",
        },
      ],
      ctaTitle: "Ready to grow your X presence?",
      ctaSubtitle: "Organize your workflow, move faster, and publish with more intention.",
      ctaButton: "Start Your Free Trial",
      ctaNote: "No credit card required",
      footer: {
        privacy: "Privacy",
        terms: "Terms",
        support: "Support",
        rights: "All rights reserved.",
      },
    },
    dashboard: {
      loadingWorkspace: "Loading workspace...",
      workspaces: "Workspaces",
      createWorkspace: "Create workspace",
      myAccount: "My account",
      overview: "Here's your X growth workspace for today.",
      currentPlanTitle: "Current plan",
      activityTitle: "Activity feed",
      activityDescription: "We removed placeholder content. This area will show live signals once your discovery pipeline is connected.",
      emptyTitle: "No live data yet",
      emptyDescription: "Connect your X workflow, configure your automations, and this dashboard will start showing real activity instead of demo content.",
      openBilling: "Open billing",
      openSettings: "Open workspace",
      goToDrafts: "Open drafts",
      planCard: "Plan",
      alertsUsed: "Alerts used today",
      alertsRemaining: "Alerts remaining",
      connectedAccounts: "Connected accounts",
      automationStatus: "Automation",
      automationReady: "Ready",
      automationRunning: "Running",
      automationDisabled: "Disabled",
      automationError: "Needs attention",
      lastRun: "Last automation run",
      unlimited: "Unlimited",
      pageTitles: {
        dashboard: "Dashboard",
        opportunities: "Opportunities",
        drafts: "Drafts",
        workspace: "Workspace",
        billing: "Billing",
      },
    },
    opportunities: {
      title: "Opportunities",
      subtitle: "Live post, quote, and reply opportunities will appear here once your discovery engine is enabled.",
      engineTitle: "Discovery engine",
      engineDescription: "No placeholder opportunities are shown here. This view stays empty until there is real data for your workspace.",
      emptyTitle: "Nothing to review yet",
      emptyDescription: "Enable your X connection, configure your workspace, and come back when the feed starts collecting live opportunities.",
    },
    drafts: {
      title: "Drafts",
      summaryDrafts: "drafts",
      summaryScheduled: "scheduled",
      newDraft: "New draft",
      createTitle: "Create new draft",
      createDescription: "Write a post and keep it saved in your workspace.",
      placeholder: "What's on your mind?",
      threadRequired: "Thread required",
      loadingDrafts: "Loading drafts...",
      cancel: "Cancel",
      saveDraft: "Save draft",
      generateAi: "Generate with AI",
      generatingAi: "Generating...",
      editTitle: "Edit draft",
      editDescription: "Update your draft before publishing it.",
      saveChanges: "Save changes",
      emptyTitle: "No drafts yet",
      emptyDescription: "Create your first real draft. We removed the fake examples from this workspace.",
      emptyCta: "Create your first draft",
      status: {
        draft: "Draft",
        scheduled: "Scheduled",
        published: "Published",
      },
      actions: {
        edit: "Edit",
        schedule: "Schedule",
        postNow: "Post now",
        delete: "Delete",
      },
      updated: "Updated",
      characters: "characters",
      source: {
        manual: "Manual",
        automation: "AI automation",
      },
    },
    settings: {
      title: "Workspace",
      subtitle: "Review the real status of this workspace, your current plan, and your X connection.",
      workspaceTitle: "Workspace details",
      workspaceDescription: "This information comes from your current session and billing config.",
      workspaceName: "Workspace name",
      workspaceSlug: "Workspace slug",
      currentPlan: "Current plan",
      connectionTitle: "X connection",
      connectionDescription: "We removed demo accounts. This section only shows the actual state of your workspace.",
      connectionStatus: "Connection status",
      connected: "Connected",
      notConnected: "Not connected",
      accountsTitle: "Account limits",
      accountsDescription: "Connected account usage for your active plan.",
      localOnlyTitle: "Workspace controls",
      localOnlyDescription: "Advanced workspace editing and notification settings are still being wired to real backend actions.",
      automationTitle: "Automation settings",
      automationDescription: "Turn Groq into a recurring draft engine for this workspace.",
      automationEnabled: "Enable autopilot",
      automationLanguage: "Draft language",
      automationTone: "Tone",
      automationTopics: "Topics",
      automationTopicsHelp: "Separate topics with commas so the generator knows what to focus on.",
      automationAudience: "Audience",
      automationBrandVoice: "Brand voice",
      automationCadence: "Cadence in minutes",
      automationMode: "Automation mode",
      automationSave: "Save automation",
      automationRunNow: "Run now",
      automationSaving: "Saving...",
      automationRunning: "Running...",
      automationSaved: "Automation settings saved.",
      automationIdle: "Idle",
      automationSuccess: "Healthy",
      automationErrorState: "Error",
      automationLastRun: "Last run",
      automationLastDraft: "Last AI draft",
      automationDraftOnly: "Create drafts only",
      toneOptions: {
        sharp: "Sharp",
        analytical: "Analytical",
        friendly: "Friendly",
      },
    },
    billing: {
      loading: "Loading billing...",
      currentPlan: "Current plan",
      currentPlanDescription: "You're currently on the",
      membershipBilling: "Membership billing",
      viewAllPlans: "View all plans",
      alertsUsedToday: "Opportunity alerts used today",
      resetNote: "Resets daily at midnight UTC",
      unlockTitle: "Unlock unlimited opportunities",
      unlockDescription: "Upgrade to Pro and remove the daily ceiling on opportunity discovery.",
      upgradeToPro: "Upgrade to Pro",
      allPlans: "All plans",
      mostPopular: "Most popular",
      current: "Current",
      currentPlanButton: "Current plan",
      upgrade: "Upgrade",
      contactSales: "Contact sales",
      paymentMethod: "Payment method",
      paymentMethodDescription: "Manage your billing setup and upgrade path",
      paymentProvider: "PayPal subscriptions",
      paymentProviderDescription: "Billing is wired for PayPal plan upgrades.",
      noInvoicesTitle: "No invoices yet",
      noInvoicesDescription: "Real invoice history will appear here after your first successful subscription charge.",
      checkoutNotReady: "PayPal checkout is not ready yet for this plan.",
      checkoutError: "Failed to create checkout flow.",
      redirecting: "Redirecting to PayPal...",
      success: "PayPal approved your subscription. We're syncing it now.",
      cancelled: "PayPal checkout was cancelled.",
      syncError: "We could not sync the PayPal subscription yet.",
      webhookState: "Webhook status",
      webhookReady: "Configured",
      webhookMissing: "Missing",
    },
    common: {
      english: "English",
      spanish: "Spanish",
      darkMode: "Dark mode",
      lightMode: "Light mode",
      loading: "Loading...",
      noData: "No data",
      save: "Save",
    },
  },
  es: {
    nav: {
      features: "Funciones",
      pricing: "Precios",
      faq: "FAQ",
      login: "Entrar",
      getStarted: "Comenzar",
      dashboard: "Panel",
      opportunities: "Oportunidades",
      drafts: "Borradores",
      workspace: "Espacio",
      billing: "Cobros",
      logout: "Cerrar sesion",
      settingsGroup: "Configuracion",
      menuGroup: "Menu",
    },
    landing: {
      badge: "Tu copiloto de crecimiento en X",
      heroTitle: "Deja de scrollear. Empieza a crecer.",
      heroSubtitle:
        "Descubre mejores oportunidades para publicar, citar y responder en X. Organiza tu contenido y construye tu audiencia con mas intencion.",
      heroCta: "Prueba gratis",
      heroSecondaryCta: "Ver como funciona",
      problemTitle: "Crecer en X no deberia sentirse como un trabajo de tiempo completo",
      problemSubtitle:
        "La mayoria de los creadores pierden horas haciendo scroll, dejan pasar oportunidades fuertes y pierden sus mejores ideas. Xsaas ordena ese caos.",
      problemCards: {
        scroll: { title: "Scroll infinito", description: "Horas perdidas buscando el post correcto para entrar a la conversacion" },
        missed: { title: "Oportunidades perdidas", description: "Los temas virales pasan antes de que puedas meter tu angulo" },
        ideas: { title: "Ideas perdidas", description: "Tus mejores borradores quedan regados entre notas y chats" },
      },
      featuresTitle: "Todo lo que necesitas para crecer con estrategia",
      featuresSubtitle: "Oportunidades filtradas, borradores ordenados e insights realmente utiles.",
      features: {
        post: {
          title: "Oportunidades de publicacion",
          description: "Detecta temas que todavia vale la pena publicar antes de que el timeline se sature.",
        },
        quote: {
          title: "Oportunidades de cita",
          description: "Encuentra posts que aun tienen inercia y espacio para que metas una cita con criterio.",
        },
        reply: {
          title: "Oportunidades de respuesta",
          description: "Sigue conversaciones donde una buena respuesta si puede mover atencion hacia tu perfil.",
        },
        drafts: {
          title: "Espacio de borradores",
          description: "Guarda ideas, ganchos y posts listos para publicar en un solo lugar.",
        },
        analytics: {
          title: "Analitica de crecimiento",
          description: "Entiende que te esta funcionando para publicar con mas confianza y menos adivinanza.",
        },
        schedule: {
          title: "Programacion inteligente",
          description: "Prepara contenido con anticipacion y mantente constante sin vivir pegado a la app.",
        },
      },
      howItWorksTitle: "Como funciona",
      howItWorksSubtitle: "Empieza en minutos y ordena tu flujo rapido.",
      steps: {
        connect: {
          title: "Configura tu cuenta",
          description: "Define temas, tono y angulos para que la app sepa que tipo de oportunidades mostrarte.",
        },
        discover: {
          title: "Descubre oportunidades",
          description: "Revisa oportunidades de post, quote y reply ordenadas por relevancia.",
        },
        create: {
          title: "Crea y organiza",
          description: "Convierte ideas en borradores, guarda tus mejores angulos y mantente listo para publicar.",
        },
        grow: {
          title: "Crece con intencion",
          description: "Mejora tu timing, tu contexto y tu organizacion para ganar mas consistencia.",
        },
      },
      pricingTitle: "Precios simples y claros",
      pricingSubtitle: "Empieza gratis y sube de plan cuando necesites mas velocidad.",
      faqTitle: "Preguntas frecuentes",
      faqSubtitle: "Lo mas importante sobre Xsaas.",
      faqs: [
        {
          question: "Como encuentra Xsaas las oportunidades?",
          answer:
            "Xsaas combina las preferencias de tu espacio con senales de la plataforma para mostrar momentos de post, quote y reply que valen la pena.",
        },
        {
          question: "Mi cuenta de X esta segura?",
          answer:
            "El producto esta pensado para trabajar con permisos minimos y separacion por workspace. La autenticacion y la publicacion viven del lado del servidor.",
        },
        {
          question: "Puedo cancelar cuando quiera?",
          answer: "Si. Tu suscripcion se puede cambiar o cancelar cuando lo necesites.",
        },
        {
          question: "Publica todo de forma automatica?",
          answer:
            "La idea es automatizar con guardrails. Tu decides que partes quedan manuales y cuales pasan a piloto automatico.",
        },
      ],
      ctaTitle: "Listo para crecer en X con mas orden?",
      ctaSubtitle: "Organiza tu flujo, muvete mas rapido y publica con mas intencion.",
      ctaButton: "Empieza tu prueba gratis",
      ctaNote: "No necesitas tarjeta",
      footer: {
        privacy: "Privacidad",
        terms: "Terminos",
        support: "Soporte",
        rights: "Todos los derechos reservados.",
      },
    },
    dashboard: {
      loadingWorkspace: "Cargando espacio...",
      workspaces: "Espacios",
      createWorkspace: "Crear espacio",
      myAccount: "Mi cuenta",
      overview: "Asi va tu espacio de trabajo hoy.",
      currentPlanTitle: "Plan actual",
      activityTitle: "Actividad",
      activityDescription: "Quitamos el contenido demo. Esta zona mostrara senales reales cuando tu pipeline de descubrimiento este conectado.",
      emptyTitle: "Todavia no hay datos reales",
      emptyDescription: "Conecta tu flujo de X, configura las automatizaciones y este panel empezara a mostrar actividad real en vez de ejemplos falsos.",
      openBilling: "Abrir cobros",
      openSettings: "Abrir espacio",
      goToDrafts: "Abrir borradores",
      planCard: "Plan",
      alertsUsed: "Alertas usadas hoy",
      alertsRemaining: "Alertas restantes",
      connectedAccounts: "Cuentas conectadas",
      automationStatus: "Automatizacion",
      automationReady: "Lista",
      automationRunning: "Corriendo",
      automationDisabled: "Apagada",
      automationError: "Requiere revision",
      lastRun: "Ultima corrida",
      unlimited: "Ilimitado",
      pageTitles: {
        dashboard: "Panel",
        opportunities: "Oportunidades",
        drafts: "Borradores",
        workspace: "Espacio",
        billing: "Cobros",
      },
    },
    opportunities: {
      title: "Oportunidades",
      subtitle: "Las oportunidades reales de post, quote y reply apareceran aqui cuando el motor de descubrimiento este activo.",
      engineTitle: "Motor de descubrimiento",
      engineDescription: "Aqui no mostramos oportunidades fake. Esta vista queda vacia hasta que exista data real para tu workspace.",
      emptyTitle: "Todavia no hay nada para revisar",
      emptyDescription: "Conecta tu flujo de X, configura el espacio y vuelve cuando el feed empiece a recolectar oportunidades reales.",
    },
    drafts: {
      title: "Borradores",
      summaryDrafts: "borradores",
      summaryScheduled: "programados",
      newDraft: "Nuevo borrador",
      createTitle: "Crear borrador",
      createDescription: "Escribe un post y guardalo en tu workspace.",
      placeholder: "Que quieres publicar?",
      threadRequired: "Necesita hilo",
      loadingDrafts: "Cargando borradores...",
      cancel: "Cancelar",
      saveDraft: "Guardar borrador",
      generateAi: "Generar con IA",
      generatingAi: "Generando...",
      editTitle: "Editar borrador",
      editDescription: "Actualiza tu borrador antes de publicarlo.",
      saveChanges: "Guardar cambios",
      emptyTitle: "Todavia no hay borradores",
      emptyDescription: "Crea tu primer borrador real. Ya quitamos los ejemplos falsos de este espacio.",
      emptyCta: "Crear tu primer borrador",
      status: {
        draft: "Borrador",
        scheduled: "Programado",
        published: "Publicado",
      },
      actions: {
        edit: "Editar",
        schedule: "Programar",
        postNow: "Publicar ahora",
        delete: "Eliminar",
      },
      updated: "Actualizado",
      characters: "caracteres",
      source: {
        manual: "Manual",
        automation: "Automatizacion IA",
      },
    },
    settings: {
      title: "Espacio",
      subtitle: "Revisa el estado real de este workspace, tu plan actual y la conexion con X.",
      workspaceTitle: "Detalles del espacio",
      workspaceDescription: "Esta informacion viene de tu sesion actual y de la configuracion de cobros.",
      workspaceName: "Nombre del espacio",
      workspaceSlug: "Slug del espacio",
      currentPlan: "Plan actual",
      connectionTitle: "Conexion con X",
      connectionDescription: "Quitamos las cuentas demo. Esta seccion solo muestra el estado real de tu workspace.",
      connectionStatus: "Estado de la conexion",
      connected: "Conectado",
      notConnected: "No conectado",
      accountsTitle: "Limites de cuentas",
      accountsDescription: "Uso de cuentas conectadas segun tu plan activo.",
      localOnlyTitle: "Controles del workspace",
      localOnlyDescription: "La edicion avanzada del espacio y las notificaciones aun se estan conectando con acciones reales de backend.",
      automationTitle: "Configuracion de automatizacion",
      automationDescription: "Convierte Groq en un motor recurrente de borradores para este workspace.",
      automationEnabled: "Activar piloto automatico",
      automationLanguage: "Idioma de borradores",
      automationTone: "Tono",
      automationTopics: "Temas",
      automationTopicsHelp: "Separa los temas con comas para que el generador sepa en que enfocarse.",
      automationAudience: "Audiencia",
      automationBrandVoice: "Voz de marca",
      automationCadence: "Cadencia en minutos",
      automationMode: "Modo de automatizacion",
      automationSave: "Guardar automatizacion",
      automationRunNow: "Correr ahora",
      automationSaving: "Guardando...",
      automationRunning: "Corriendo...",
      automationSaved: "Configuracion de automatizacion guardada.",
      automationIdle: "En espera",
      automationSuccess: "Saludable",
      automationErrorState: "Con error",
      automationLastRun: "Ultima corrida",
      automationLastDraft: "Ultimo borrador IA",
      automationDraftOnly: "Solo crear borradores",
      toneOptions: {
        sharp: "Filoso",
        analytical: "Analitico",
        friendly: "Cercano",
      },
    },
    billing: {
      loading: "Cargando cobros...",
      currentPlan: "Plan actual",
      currentPlanDescription: "Ahora mismo estas en el plan",
      membershipBilling: "Cobro por membresia",
      viewAllPlans: "Ver todos los planes",
      alertsUsedToday: "Alertas usadas hoy",
      resetNote: "Se reinicia cada dia a medianoche UTC",
      unlockTitle: "Desbloquea oportunidades ilimitadas",
      unlockDescription: "Sube a Pro y quita el limite diario del descubrimiento de oportunidades.",
      upgradeToPro: "Subir a Pro",
      allPlans: "Todos los planes",
      mostPopular: "Mas popular",
      current: "Actual",
      currentPlanButton: "Plan actual",
      upgrade: "Mejorar",
      contactSales: "Contactar ventas",
      paymentMethod: "Metodo de pago",
      paymentMethodDescription: "Administra tu configuracion de cobro y el camino de upgrade",
      paymentProvider: "Suscripciones con PayPal",
      paymentProviderDescription: "La facturacion esta preparada para upgrades con PayPal.",
      noInvoicesTitle: "Todavia no hay facturas",
      noInvoicesDescription: "El historial real aparecera aqui despues del primer cobro exitoso de suscripcion.",
      checkoutNotReady: "Todavia no esta listo el checkout de PayPal para este plan.",
      checkoutError: "No se pudo crear el checkout.",
      redirecting: "Redirigiendo a PayPal...",
      success: "PayPal aprobo tu suscripcion. La estamos sincronizando.",
      cancelled: "El checkout de PayPal fue cancelado.",
      syncError: "Todavia no pudimos sincronizar la suscripcion de PayPal.",
      webhookState: "Estado del webhook",
      webhookReady: "Configurado",
      webhookMissing: "Falta configurar",
    },
    common: {
      english: "English",
      spanish: "Espanol",
      darkMode: "Modo noche",
      lightMode: "Modo claro",
      loading: "Cargando...",
      noData: "Sin datos",
      save: "Guardar",
    },
  },
} as const

export type Language = keyof typeof copy
export type AppCopy = (typeof copy)[Language]
